// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function mockableFunctionBody(functionName, storageParameters, mockerParameterCalls) {
  return "\nif(shouldUseMock && keccak256(abi.encodePacked(functionToNotMock)) != keccak256(abi.encodePacked(\"" + functionName + "\"))){\n  " + storageParameters + "\n  return mocker." + functionName + "Mock(" + mockerParameterCalls + ");\n} else {\n  return super." + functionName + "(" + mockerParameterCalls + ");\n}\n}\n";
}

function externalMockerFunctionBody(functionName, mockerArguments, mockerReturnValues, mockerReturn) {
  return "\n  function " + functionName + "Mock(" + mockerArguments + ") public pure " + mockerReturnValues + "{\n    return (" + mockerReturn + ");\n  }\n";
}

function mockableModifierBody(functionName, storageParameters, mockerParameterCalls, functionBody) {
  return "\nif(shouldUseMock && keccak256(abi.encodePacked(functionToNotMock)) != keccak256(abi.encodePacked(\"" + functionName + "\"))){\n  " + storageParameters + "\n  mocker." + functionName + "Mock(" + mockerParameterCalls + ");\n  _;\n} else {\n  " + functionBody + "\n}\n}\n";
}

function externalMockerModifierBody(functionName, mockerArguments) {
  return "\nfunction " + functionName + "Mock(" + mockerArguments + ") public pure {}\n";
}

function internalMockingFileTemplate(fileNameWithoutExtension, parentImports, contractBody) {
  return "// SPDX-License-Identifier: BUSL-1.1 \n pragma solidity 0.8.13;\n\nimport \"./" + fileNameWithoutExtension + "Mockable.sol\";\nimport \"../" + fileNameWithoutExtension + "InternalStateSetters.sol\";\n\n" + parentImports + "\n\ncontract " + fileNameWithoutExtension + "ForInternalMocking {\n  " + contractBody + "\n}";
}

function constructor(paramsWithTypes, params, fileNameWithoutExtension) {
  return "constructor(" + paramsWithTypes + ") " + fileNameWithoutExtension + "InternalStateSetters(" + params + ") {}";
}

function mockingFileTemplate(prefix, fileNameWithoutExtension, fullBody, constructor) {
  return prefix + "\nimport \"./" + fileNameWithoutExtension + "ForInternalMocking.sol\";\nimport \"../" + fileNameWithoutExtension + "InternalStateSetters.sol\";\n\ncontract " + fileNameWithoutExtension + "Mockable is " + fileNameWithoutExtension + "InternalStateSetters {\n\n  " + fileNameWithoutExtension + "ForInternalMocking mocker;\n  bool shouldUseMock;\n  string functionToNotMock;\n\n  " + constructor + "\n\n  function setMocker(" + fileNameWithoutExtension + "ForInternalMocking _mocker) external {\n    mocker = _mocker;\n  }\n\n  function disableMocker() external {\n    shouldUseMock = false;\n  }\n\n  function setFunctionToNotMock(string calldata _functionToNotMock) external {\n    functionToNotMock = _functionToNotMock;\n    shouldUseMock = true;\n  }\n\n" + fullBody + "\n}\n";
}

exports.mockableFunctionBody = mockableFunctionBody;
exports.externalMockerFunctionBody = externalMockerFunctionBody;
exports.mockableModifierBody = mockableModifierBody;
exports.externalMockerModifierBody = externalMockerModifierBody;
exports.internalMockingFileTemplate = internalMockingFileTemplate;
exports.constructor = constructor;
exports.mockingFileTemplate = mockingFileTemplate;
/* No side effect */
